#!/usr/bin/env ansible-playbook

- name: install cloud
  hosts: cloud
  become: true

  roles:
    - prep_ufw
    - { role: prep_os, when: (state is undefined or 'absent' not in state) }
    - { role: prep_docker, when: (state is undefined or 'absent' not in state) }
    - docker_container
    - { role: prep_backup, when: restic_repo != '' }
    - { role: do_dynamic_dns, when: configure_do_dynamic_dns|bool }
