---
# tasks file to start adminer container

- name: "{{ 'Create' if (state is undefined or 'absent' not in state) else 'Terminate' }} adminer container"
  docker_container:
    name: adminer
    image: adminer:{{ docker_adminer_image }}
    restart_policy: always
    tty: yes
    links: 
      - 'cloud-db:db'
    networks:
      - name: backend
    networks_cli_compatible: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.adminer.entrypoints: "web-secure"
      traefik.http.routers.adminer.rule: "Host(`{{ cloud_server_fqdn }}`) && (Path(`/adminer/`) || Path(`/adminer`))"
      traefik.http.services.adminer.loadbalancer.server.port: "8080"
      com.centurylinklabs.watchtower.enable: "true"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://adminer:8080/ || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
    state: "{{ state | default('started') }}"
      