---

- name: adding element-config.json file
  template:
    src: element-config.json.j2
    dest: "{{ cloud_base_dir }}/element/element-config.json"
    owner: root
    group: root

- name: "{{ 'Create' if (state is undefined or 'absent' not in state) else 'Terminate' }} the element container"
  docker_container:
    name: element
    image: "vectorim/element-web"
    restart_policy: unless-stopped
    networks:
      - name: backend
    networks_cli_compatible: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.element.entrypoints: "web-secure"      
      traefik.http.routers.element.rule: "Host(`chat.{{ cloud_server_fqdn }}`)"
      traefik.http.routers.element.service: matrix
      traefik.http.services.element.loadbalancer.server.port: "80"
      com.centurylinklabs.watchtower.enable: "true"

    volumes:
      - "{{ cloud_base_dir }}/element/element-config.json:/app/config.json"
    state: "{{ state | default('started') }}"

