---
# tasks file for docker_container
# start all needed container

- name: docker | network
  include_tasks: network.yml
  when: state is undefined or 'absent' not in state

- name: docker | watchtower
  include_tasks: watchtower.yml

- name: docker | dockerproxy
  include_tasks: dockerproxy.yml

- name: docker | traefik
  include_tasks:
    file: traefik.yml
    apply:
      tags: traefik
  tags: traefik

- name: docker | portainer
  include_tasks: portainer.yml
  when: portainer_enabled|bool

- name: docker | postgres
  include_tasks:
    file: postgres.yml
    apply:
      tags: postgres
  tags: postgres

- name: docker | redis
  include_tasks: redis.yml

- name: docker | nextcloud
  include_tasks: nextcloud.yml
  tags: nextcloud

- name: docker | onlyoffice
  include_tasks: onlyoffice.yml
  tags: onlyoffice

- name: docker | nginx
  include_tasks: 
    file: nginx.yml
    apply:
      tags: nginx
  tags: nginx

- name: docker | synapse
  include_tasks: synapse.yml
  tags: synapse

- name: docker | matrix registration
  include_tasks: matrix-registration.yml

- name: docker | element
  include_tasks: element.yml
  tags: element

- name: docker | ntfy
  include_tasks: ntfy.yml
  tags: ntfy

- name: docker | immich
  include_tasks:
    file: immich.yml
    apply:
      tags: immich
  tags: immich

- name: docker | actual budget
  include_tasks:
    file: actual.yml
    apply:
      tags: actual
  tags: actual
