---
# tasks file for docker_container
# start all needed container

- name: docker network
  include_tasks: network.yml
  when: state is undefined or 'absent' not in state

- name: docker watchtower
  include_tasks: watchtower.yml

- name: docker dockerproxy
  include_tasks: dockerproxy.yml

- name: docker traefik
  include_tasks:
    file: traefik.yml
    apply:
      tags: traefik
  tags: traefik

- name: docker portainer
  include_tasks: portainer.yml
  when: portainer_enabled|bool

- name: docker postgres
  include_tasks:
    file: postgres.yml
    apply:
      tags: postgres
  tags: postgres

- name: docker redis
  include_tasks: redis.yml

- name: docker adminer
  include_tasks: adminer.yml
  when:
    - adminer_enabled|bool

- name: docker nextcloud
  include_tasks: nextcloud.yml

- name: docker onlyoffice
  include_tasks: onlyoffice.yml
  tags: onlyoffice

- name: docker nginx
  include_tasks: nginx.yml
  when: "'fpm' in docker_nextcloud_image"

- name: docker turnserver
  include_tasks: turnserver.yml
  when:
    - (ansible_architecture == 'x86_64' or ansible_architecture == 'aarch64')

- name: docker elasticsearch_tesseract
  include_tasks: elasticsearch.yml
  when:
    - fulltextsearch_enabled|bool

- name: docker elasticsearch_tesseract
  include_tasks: elasticsearch.yml
  when:
    - fulltextsearch_enabled|bool

- name: docker synapse
  include_tasks: synapse.yml
  tags: synapse

- name: matrix registration
  include_tasks: matrix-registration.yml

- name: docker element
  include_tasks: element.yml

- name: docker wireguard
  include_tasks: wireguard.yml

- name: docker photoprism
  include_tasks:
    file: photoprism.yml
    apply:
      tags: photos
  tags: photos

- name: docker network
  include_tasks: network.yml
  when: state is defined and 'absent' in state
