---
# tasks file to start redis container

- name: "{{ 'Create' if (state is undefined or 'absent' not in state) else 'Terminate' }} redis container"
  docker_container:
    name: redis
    image: redis:{{ docker_redis_image | default('latest') }}
    restart_policy: always
    command: redis-server --requirepass {{ redis_secret }}
    networks:
      - name: backend
    networks_cli_compatible: true
    volumes:
      - 'redis-data-vol:/data:rw'
    labels:
      com.centurylinklabs.watchtower.enable:         "true"
    state: "{{ state | default('started') }}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
