---
# tasks file to start turnserver container
- name: ensures turn dir exists
  file:
    path: "{{ cloud_coturn_dir }}"
    state: directory
    owner: root
    group: root

- name: get public IP
  ipify_facts:
  register: public_ip

- name: copy turnserver.conf
  template:
    src: "turnserver.conf.j2"
    dest: "{{ cloud_coturn_dir }}/turnserver.conf"
    owner: "root"
    group: "root"
    mode: 0644

- name: "{{ 'Create' if (state is undefined or 'absent' not in state) else 'Terminate' }} the turnserver container"
  docker_container:
    name: "turn_server"
    image: "{{ 'serverror' if ansible_architecture == 'aarch64' else 'coturn' }}/coturn:{{ docker_turnserver_image | default('latest') }}"
    restart_policy: "unless-stopped"
    volumes:
      - "turnserver-data-vol:/var/lib/coturn:rw"
      - "{{ cloud_coturn_dir }}/turnserver.conf:/etc/coturn/turnserver.conf"
    network_mode: host
    state: '{{ state | default("started") }}'
