---
# vars file for docker_container

nextcloud_traefik_label:
  nginx:
    traefik.enable: "false"
    com.centurylinklabs.watchtower.enable: "true"
    com.centurylinklabs.watchtower.depends-on: "nginx,redis{% if nextcloud_db_type != 'sqlite' %},cloud-db{% endif %}"

  apache:
    traefik.enable: "true"
    traefik.http.routers.cloud.entrypoints: "web-secure"
    traefik.http.routers.cloud.rule: "Host(`{{ cloud_server_fqdn }}`)"
    traefik.http.routers.cloud.middlewares: "nextcloud@file"
    traefik.http.routers.nginx.service: "cloud"
    traefik.http.services.nginx.loadbalancer.server.port: "80"
    com.centurylinklabs.watchtower.enable: "true"
    com.centurylinklabs.watchtower.depends-on: "redis,cloud-db"

service_path:
  CentOS: "/usr/lib/systemd/system"
  Fedora: "/usr/lib/systemd/system"
  Amazon: "/usr/lib/systemd/system"
  Ubuntu: "/lib/systemd/system"
  Debian: "/lib/systemd/system"
