---
- name: install talk app
  shell: "{{ docker_occ_cmd }} app:install spreed"
  args:
    creates: "{{ nextcloud_www_dir }}/apps/spreed"
  register: talk_app_installed

- name: configure talk app
  shell: "{{ docker_occ_cmd }} {{ item }}"
  loop:
    - app:enable spreed
    - config:app:set spreed stun_servers --value '["{{ cloud_server_fqdn }}:3478"]'
    - config:app:set spreed turn_servers --value '[{"server":"{{ cloud_server_fqdn }}:3478","secret":"{{ lookup('password', '{{ local_credential_store }}/coturn_secret chars=ascii_letters,digits length=32') | lower }}","protocols":"udp,tcp"}]'
  when: talk_app_installed is changed

- name: open ufw firewall
  include_role:
    name: prep_ufw
  vars:
    ufw_rules:
      - { port: "3478", proto: "tcp", rule: "allow" }
      - { port: "3478", proto: "udp", rule: "allow" }
  when: ( ansible_os_family == "Debian" or ansible_os_family == "Ubuntu" ) and talk_app_installed is changed
