---
# install and configure rclone

- name: install latest rclone debian package
  apt: 
    deb: '{{ rclone_download_url }}.deb'
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: install latest rclone rpm package
  yum: 
    name: '{{ rclone_download_url }}.rpm'
    state: present
  when: ansible_pkg_mgr == 'yum'

- name: make sure rclone config folder exists
  file:
    name: '/root/.config/rclone'
    owner:   'root'
    group:   'root'
    mode:    '0700'
    state:   directory

- name: create rclone config 
  template:
    src: rclone.conf.j2
    dest:    '/root/.config/rclone/rclone.conf'
    owner:   'root'
    group:   'root'
    mode:    '0600'