---
# tasks file for dynamic_dns

- name: install python requests package
  pip:
    name: requests

- name: create dynamic_dns update script
  template:
    src: "dynamic_dns_check.py.j2"
    dest: "/usr/local/bin/dynamic_dns_check.py"
    owner: "root"
    group: "root"
    mode: "0750"
    force: false

- name: cron dynamic_dns update
  cron:
    name: "Check dynamic dns"
    minute: "*/5"
    job: "/usr/local/bin/dynamic_dns_check.py > /var/log/dynamic_dns_check.log 2>&1"
